export const LANGUAGE_COLOR_MAP = {
  javascript: '#fff0e5',
  python: '#C4FCEF',
  java: '#fff0e5',
  'c++': '#eec2ff',
  c: '#eec2ff',
  php: '#ece5f5',
  'c#': '#ece5f5',
  shell: '#C4FCEF',
  go: '#d4f5ff',
  typescript: '#fff0e5',
  ruby: '#fbf3ff',
  'objective-c': '#438eff',
  swift: '#C4FCEF',
  kotlin: '#fbf3ff',
  r: '#fbf3ff',
  scala: '#fbf3ff',
  rust: '#eec2ff',
  lua: '#d4f5ff',
  matlab: '#eec2ff',
  coffeescript: '#fff0e5',
  perl: '#d4f5ff',
  groovy: '#e5f8ff',
  haskel: '#C4FCEF',
};
