export const SEARCH_DEBOUNCE_INTERVAL = 500;
export const LIST_ITEMS_PER_PAGE = 50;

export const GOOGLE = {
  API_KEY: process.env.GRS_GOOGLE_API_KEY,
  TIMEZONE_API_URL: process.env.GRS_GOOGLE_API_URL,
};

export const GITHUB = {
  API_URL: process.env.GRS_GITHUB_API_URL,
  CONTENT_URL: process.env.GRS_GITHUB_CONTENT_URL,
  OAUTH_AUTHORIZATION_URL: process.env.GRS_OAUTH_AUTHORIZATION_URL,
  GRS_OAUTH_TOKEN_URL: process.env.OAUTH_TOKEN_URL,
};

export const APP = {
  GITHUB_CLIENT_ID: process.env.GRS_GITHUB_CLIENT_ID,
  GITHUB_CLIENT_SECRET: process.env.GRS_GITHUB_CLIENT_SECRET,
  GITHUB_SECRET_KEY: process.env.GRS_GITHUB_SECRET_KEY,
  GOOGLE_API_KEY: process.env.GRS_GOOGLE_API_KEY,
  DOMAIN: process.env.GRS_DOMAIN,
  PROXY_SERVER_URL: process.env.GRS_PROXY_SERVER_URL,
};
